default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"
  lane :deploy do
    # API Key setup for authentication without interactive login
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      duration: 1200,
      in_house: false
    )

    # Otomatik build numarasını artır (Her seferinde farklı numara olması için)
    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"], # GitHub'daki her işlem numarası bir build numarası olur
      xcodeproj: "ios/App/App.xcodeproj"
    )

    # Sync certificates...
    build_app(
      scheme: "App",
      workspace: "ios/App/App.xcworkspace",
      include_bitcode: false,
      export_method: "app-store",
      api_key: api_key
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
