opt_out_usage

default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"
  lane :deploy do
    bundle_id = "com.osmanileri.echoshift"
    team_id = ENV["APPLE_TEAM_ID"]

    # 1. API Key Auth
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      duration: 1200,
      in_house: false
    )

    update_project_team(path: "ios/App/App.xcodeproj", teamid: team_id)
    update_app_identifier(xcodeproj: "ios/App/App.xcodeproj", plist_path: "App/Info.plist", app_identifier: bundle_id)

    increment_build_number(build_number: ENV["GITHUB_RUN_NUMBER"], xcodeproj: "ios/App/App.xcodeproj")

    # 4. Sertifika Yonetimi
    # force: true -> Gerekirse yenisini olusturur (ama limit varsa hata verir, silmen lazim)
    cert(
      api_key: api_key, 
      development: false
    )

    # force: true -> Profili zorla yeniler
    sigh(
      api_key: api_key,
      app_identifier: bundle_id,
      force: true,
      team_id: team_id,
      provisioning_name: "AppStore_#{bundle_id}" # Ismi sabitliyoruz
    )

    # 5. Build
    build_app(
      scheme: "App",
      project: "ios/App/App.xcodeproj",
      export_method: "app-store",
      api_key: api_key,
      include_bitcode: false,
      clean: true,
      export_options: {
        provisioningProfiles: { 
          bundle_id => "AppStore_#{bundle_id}" 
        }
      },
      xcargs: "DEVELOPMENT_TEAM=#{team_id} PROVISIONING_PROFILE_SPECIFIER='AppStore_#{bundle_id}' CODE_SIGN_STYLE=Manual"
    )

    # 6. Upload
    upload_to_testflight(api_key: api_key, app_identifier: bundle_id, skip_waiting_for_build_processing: true)
  end
end
